export const Data = [
    {
        question: "What is the value of π (pi) to two decimal places?",
        option1: "a) 3.14",
        option2: "b) 3.12",
        option3: "c) 3.16",
        option4: "d) 3.18",
        ans: 1,
    },
    {
        question: "What is the result of 5 multiplied by 9?",
        option1: "a) 45",
        option2: "b) 54",
        option3: "c) 59",
        option4: "d) 50",
        ans: 1,
    },
    {
        question: "What is the square root of 64?",
        option1: "a) 6",
        option2: "b) 8",
        option3: "c) 10",
        option4: "d) 12",
        ans: 2,
    },
    {
        question: "If a triangle has angles measuring 45°, 45°, and 90°, what type of triangle is it?",
        option1: "a) Equilateral",
        option2: "b) Isosceles",
        option3: "c) Scalene",
        option4: "d) Right",
        ans: 4,
    },
    {
        question: "What is the result of 12 divided by 4?",
        option1: "a) 2",
        option2: "b) 3",
        option3: "c) 4",
        option4: "d) 5",
        ans: 2,
    },
    {
        question: "What is the value of 2 to the power of 5?",
        option1: "a) 8",
        option2: "b) 10",
        option3: "c) 16",
        option4: "d) 32",
        ans: 1,
    },
    {
        question: "If x = 5 and y = 3, what is the value of 2x + y?",
        option1: "a) 10",
        option2: "b) 13",
        option3: "c) 11",
        option4: "d) 15",
        ans: 3,
    },
    {
        question: "What is the result of 7 minus 2?",
        option1: "a) 4",
        option2: "b) 5",
        option3: "c) 6",
        option4: "d) 7",
        ans: 2,
    },
    {
        question: "What is the perimeter of a rectangle with length 5 units and width 3 units?",
        option1: "a) 10 units",
        option2: "b) 12 units",
        option3: "c) 15 units",
        option4: "d) 16 units",
        ans: 3,
    },
    {
        question: "If a = 2 and b = 3, what is the value of a² + b²?",
        option1: "a) 7",
        option2: "b) 10",
        option3: "c) 13",
        option4: "d) 15",
        ans: 3,
    },
    {
        question: "What is the result of 8 plus 6?",
        option1: "a) 12",
        option2: "b) 13",
        option3: "c) 14",
        option4: "d) 15",
        ans: 3,
    },
    {
        question: "What is the area of a square with side length 10 units?",
        option1: "a) 40 square units",
        option2: "b) 50 square units",
        option3: "c) 80 square units",
        option4: "d) 100 square units",
        ans: 4,
    },
    {
        question: "If a circle has a radius of 4 units, what is its circumference?",
        option1: "a) 8π units",
        option2: "b) 12π units",
        option3: "c) 16π units",
        option4: "d) 24π units",
        ans: 3,
    },
    {
        question: "What is the result of 3 multiplied by 7, then added to 5?",
        option1: "a) 16",
        option2: "b) 21",
        option3: "c) 26",
        option4: "d) 35",
        ans: 3,
    },
    {
        question: "What is the volume of a cube with side length 3 units?",
        option1: "a) 9 cubic units",
        option2: "b) 18 cubic units",
        option3: "c) 27 cubic units",
        option4: "d) 36 cubic units",
        ans: 3,
    },
    {
        question: "If x = 4 and y = 7, what is the value of 3x - 2y?",
        option1: "a) -1",
        option2: "b) 1",
        option3: "c) 11",
        option4: "d) 14",
        ans: 1,
    },
    {
        question: "What is the result of 10 divided by 2?",
        option1: "a) 3",
        option2: "b) 4",
        option3: "c) 5",
        option4: "d) 6",
        ans: 3,
    },
    {
        question: "If a rectangle has length 8 units and width 5 units, what is its area?",
        option1: "a) 30 square units",
        option2: "b) 35 square units",
        option3: "c) 40 square units",
        option4: "d) 45 square units",
        ans: 2,
    },
    {
        question: "What is the result of 15 minus 9?",
        option1: "a) 4",
        option2: "b) 5",
        option3: "c) 6",
        option4: "d) 7",
        ans: 1,
    },
    {
        question: "If a triangle has sides measuring 3 units, 4 units, and 5 units, what type of triangle is it?",
        option1: "a) Equilateral",
        option2: "b) Isosceles",
        option3: "c) Scalene",
        option4: "d) Right",
        ans: 4,
    }

];
